version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  flink-jobmanager:
    image: flink:1.14
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

  flink-taskmanager:
    image: flink:1.14
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

  spark-master:
    image: bitnami/spark:3.3
    ports:
      - "8080:8080"
    command: master
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:3.3
    depends_on:
      - spark-master
    command: worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  ranking-service:
    build: ./ranking-service
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - spark-master
    environment:
      SPRING_REDIS_HOST: redis
      HIVE_JDBC_URL: jdbc:hive2://spark-master:10000/default
      RANKING_FORMULA: "0.4*CTR + 0.3*CVR + 0.3*REPURCHASE"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure/grafana/dashboard.json:/etc/grafana/provisioning/dashboards/ecommerce.json